version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: "db"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - bot-net

  tg_bot:
    container_name: "tg-bot"
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: poetry run python main.py
    env_file:
      - .env
    volumes:
      - ./bot/:/workspace/
    depends_on:
      - db
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.138.0.0/24