[tool.poetry]
name = "tg-bot"
version = "0.1.0"
description = ""
authors = ["Semen Sorokatyi <ssorokatiy@nedra.digital>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pytelegrambotapi = "^4.22.1"
pydantic-settings = "^2.5.2"
aiohttp = "^3.10.5"
steampy = "^1.1.2"
watchdog = "^6.0.0"
psutil = "^7.0.0"
sqlalchemy = "^2.0.38"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
